import { Client } from '../types';
import { subDays, formatISO } from 'date-fns';

function daysAgo(n: number): string {
  return formatISO(subDays(new Date(), n), { representation: 'date' });
}

export const SAMPLE_CLIENTS: Client[] = [
  {
    id: '1',
    name: 'Aria Nakamura',
    company: 'Nexus Digital',
    email: 'aria@nexusdigital.io',
    industry: 'Technology',
    lastContactDate: daysAgo(3),
    monthlyRevenue: 12000,
    satisfactionRating: 9,
    notes: 'Key strategic partner. Expanding to two more teams next quarter.',
    createdAt: daysAgo(180),
    updatedAt: daysAgo(3),
  },
  {
    id: '2',
    name: 'Marcus Osei',
    company: 'Goldcrest Ventures',
    email: 'marcus@goldcrest.vc',
    industry: 'Finance',
    lastContactDate: daysAgo(22),
    monthlyRevenue: 8500,
    satisfactionRating: 6,
    notes: 'Mentioned concerns about onboarding speed. Schedule a check-in soon.',
    createdAt: daysAgo(90),
    updatedAt: daysAgo(22),
  },
  {
    id: '3',
    name: 'Priya Sharma',
    company: 'Verdant Health',
    email: 'priya@verdanthealth.co',
    industry: 'Healthcare',
    lastContactDate: daysAgo(72),
    monthlyRevenue: 3200,
    satisfactionRating: 4,
    notes: 'Last call went poorly. Contract renewal is in 6 weeks — urgent intervention needed.',
    createdAt: daysAgo(240),
    updatedAt: daysAgo(72),
  },
  {
    id: '4',
    name: 'Leon Bouchard',
    company: 'Atelier Créatif',
    email: 'leon@ateliercrea.fr',
    industry: 'Design',
    lastContactDate: daysAgo(5),
    monthlyRevenue: 4800,
    satisfactionRating: 8,
    notes: 'Referred two new clients last month. Very happy with service delivery.',
    createdAt: daysAgo(120),
    updatedAt: daysAgo(5),
  },
  {
    id: '5',
    name: 'Tomás Reyes',
    company: 'Orbita Consulting',
    email: 'tomas@orbita.mx',
    industry: 'Consulting',
    lastContactDate: daysAgo(45),
    monthlyRevenue: 6000,
    satisfactionRating: 5,
    notes: 'Slow to respond to emails. Revenue is stable but engagement is dropping.',
    createdAt: daysAgo(150),
    updatedAt: daysAgo(45),
  },
  {
    id: '6',
    name: 'Yuki Tanaka',
    company: 'Luminara Studio',
    email: 'yuki@luminara.jp',
    industry: 'Media',
    lastContactDate: daysAgo(100),
    monthlyRevenue: 1800,
    satisfactionRating: 3,
    notes: 'At serious risk of churn. Has not responded to last 3 outreach attempts.',
    createdAt: daysAgo(300),
    updatedAt: daysAgo(100),
  },
  {
    id: '7',
    name: 'Simone DuBois',
    company: 'Paragon Retail',
    email: 'simone@paragonretail.com',
    industry: 'Retail',
    lastContactDate: daysAgo(10),
    monthlyRevenue: 22000,
    satisfactionRating: 10,
    notes: 'Best client. Always pays early and provides excellent referrals.',
    createdAt: daysAgo(365),
    updatedAt: daysAgo(10),
  },
  {
    id: '8',
    name: 'Kwame Asante',
    company: 'BuildRight Ltd',
    email: 'kwame@buildright.gh',
    industry: 'Construction',
    lastContactDate: daysAgo(55),
    monthlyRevenue: 2200,
    satisfactionRating: 6,
    notes: 'Seasonal business — contact usually drops in Q1. Follow up in April.',
    createdAt: daysAgo(200),
    updatedAt: daysAgo(55),
  },
];
